name: ByteEater

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macOS-latest]
  
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.16.x'
    - name: Use cmake
      run: cmake --version
    
    - if: runner.os == 'Linux'
      name: ubuntu-build
      run: buildUnixDarwin.sh
      
    - if: runner.os == 'macOS'
      name: macOS-build
      run: buildUnixDarwin.sh
      
    - if: runner.os == 'Windows'
      name: windows-build
      run: buildWin.bat
